# experiments/config.py
"""
Defines the generic data structures for configuring experiments.
This allows for specifying any environment and agent population, making
the framework fully extensible.
"""
from dataclasses import dataclass, field
from typing import List, Dict, Any, Optional

@dataclass
class AgentPopulationConfig:
    """Specifies a subgroup of agents to be created for a simulation."""
    agent_class_path: str  # e.g., 'environments.democracy.agents.AlignedLLMAgent'
    count: int             # The number of agents of this type to create.

@dataclass
class ExperimentConfig:
    """
    A generic, high-level definition of an experimental suite.
    """
    # --- Experiment Metadata ---
    name: str  # Unique name for this experimental suite.

    # --- Environment Specification ---
    # Python path to the Environment class to be instantiated.
    environment_class_path: str
    # A dictionary of parameters to pass to the environment's configuration object.
    environment_params: Dict[str, Any]

    # --- Agent Population Specification ---
    # A list defining the mix of agent populations for the environment.
    agent_populations: List[AgentPopulationConfig]
    
    # --- Experimental Design ---
    # A dictionary of parameters to sweep. Keys are param names, values are lists of values.
    # e.g., {'environment_params.num_adversarial': [2, 4, 6]}
    parameter_sweeps: Dict[str, List[Any]]
    
    # --- Execution Parameters ---
    num_replications_per_setting: int
    base_seed: int

@dataclass
class SingleRunParams:
    """
    A flat dictionary-like object containing all parameters for one worker process.
    This is generated by expanding an ExperimentConfig.
    """
    run_id: int
    experiment_name: str
    replication_index: int
    seed: int
    environment_class_path: str
    agent_population_configs: List[Dict[str, Any]]
    environment_params: Dict[str, Any]